server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/useradmin?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: aniketkaushik1A@
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect